// src/data/product.js
export const products = [
  {
    id: 1,
    category: "Smart TVs",
    name: "Samsung Crystal UHD",
    price: "10799.00",
    image: "/assets/Smart Tv's.webp",
    labels: ["New"],
  },
  {
    id: 2,
    category: "Smartphones",
    name: "iPhone 14 Pro",
    price: "10,099.00",
    originalPrice: "14,199.00",
    image: "/assets/Iphone 14.webp", // Fixed path
    labels: ["Sale", "Best Choice"],
  },
  {
    id: 3,
    category: "Smartwatches",
    name: "Apple Watch Series 8",
    price: "8399.00",
    image: "/assets/apple watch.webp",
    labels: ["New"],
  },
  {
    id: 4,
    category: "Gadgets",
    name: "PS5 1TB",
    price: "11,499.00",
    image: "/assets/Gaming console.png",
    labels: ["Best Choice"],
  },
  {
    id: 5,
    category: "Gadgets",
    name: "Dr Dre Beats",
    price: "6129.00",
    image: "/assets/dr dre beats.webp",
    labels: [],
  },
    {
    id: 6,
    category: "Gadgets",
    name: "Neon Green Xbox one Remote",
    price: "899.00",
    image: "/assets/xbox one Remote1.jpg",
    labels: ["Hot Seller"],
  },
    {
    id: 7,
    category: "Gadgets",
    name: "Nintendo Switch one 64GB",
    price: "3129.00",
    image: "/assets/nintendo switch.jpg",
    labels: [],
  },
     {
    id: 8,
    category: "Gadgets",
    name: "Apple iPad Pro",
    price: "22.999.00",
    image: "/assets/ipad Pro.jpg",
    labels: [],
  },
     {
    id: 9,
    category: "Gadgets",
    name: "ADMI Gaming Ryzen 7 2500x",
    price: "21.600.00",
    image: "/assets/ADMI Gaming pc.jpg",
    labels: [],
  },
     {
    id: 10,
    category: "Gadgets",
    name: "4k camera Drone 2.4GHz wireless",
    price: "599.00",
    image: "/assets/Drone01.jpg",
    labels: [],
  },
];